language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "k7g6TtiShJMKUO6PO8j1TexfHA1UIu2vJ/aUztOG+AxTNbIkGYEgVf9Yxu/fDLMjdo2tRPjUXRoOKFgJlkbharrdsusAqfcmdvqV9Z/XztqnrjRMmsyJDtC2hKQpKQrV7yFY43vNnf8ywFFD4oj/UXFTDUP+TGJj8MvNefJIE3A="

addons:
  coverity_scan:
    project:
      name: "petergeneric/ebs-snapshotd"
      description: "Daemon to create snapshots of EBS volumes on a scheduled basis and clear up older snapshots over time"
    notification_email: peter@peterphi.com
    build_command_prepend:
    build_command:
    branch_pattern: master
